import { useState, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import {
  Share2,
  Printer,
  Copy,
  Check,
  Download,
  ClipboardList,
  MessageSquare,
} from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { PrintableRecipe } from "./PrintableRecipe";

interface Ingredient {
  item: string;
  amount: string;
  notes?: string;
}

interface Nutrition {
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
}

interface Meal {
  name: string;
  type: "breakfast" | "lunch" | "dinner" | "snack";
  prepTime: string;
  cookTime: string;
  servings: number;
  safetyScore: number;
  ingredients: Ingredient[];
  instructions: string[];
  nutrition: Nutrition;
  healthBenefits: string[];
  warnings: string[];
}

interface MealPlan {
  meals: Meal[];
  shoppingList: string[];
  tips: string[];
}

interface ShareMealPlanProps {
  mealPlan?: MealPlan;
  singleMeal?: Meal;
}

export const ShareMealPlan = ({ mealPlan, singleMeal }: ShareMealPlanProps) => {
  const { toast } = useToast();
  const [isOpen, setIsOpen] = useState(false);
  const [copied, setCopied] = useState<string | null>(null);
  const printRef = useRef<HTMLDivElement>(null);

  const meals = singleMeal ? [singleMeal] : mealPlan?.meals || [];
  const shoppingList = mealPlan?.shoppingList || [];

  const copyToClipboard = async (text: string, type: string) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(type);
      toast({
        title: "Copied!",
        description: `${type} copied to clipboard`,
      });
      setTimeout(() => setCopied(null), 2000);
    } catch (error) {
      toast({
        title: "Copy Failed",
        description: "Could not copy to clipboard",
        variant: "destructive",
      });
    }
  };

  const generateRecipeText = (meal: Meal) => {
    let text = `🍽️ ${meal.name}\n`;
    text += `━━━━━━━━━━━━━━━━━━━━\n`;
    text += `⏱️ Prep: ${meal.prepTime} | Cook: ${meal.cookTime}\n`;
    text += `👥 Servings: ${meal.servings} | 🔥 ${meal.nutrition.calories} cal\n\n`;

    text += `📝 INGREDIENTS:\n`;
    meal.ingredients.forEach((ing) => {
      text += `• ${ing.amount} ${ing.item}${ing.notes ? ` (${ing.notes})` : ""}\n`;
    });

    text += `\n📋 INSTRUCTIONS:\n`;
    meal.instructions.forEach((step, i) => {
      text += `${i + 1}. ${step}\n`;
    });

    text += `\n💪 NUTRITION:\n`;
    text += `Calories: ${meal.nutrition.calories} | Protein: ${meal.nutrition.protein}g\n`;
    text += `Carbs: ${meal.nutrition.carbs}g | Fat: ${meal.nutrition.fat}g | Fiber: ${meal.nutrition.fiber}g\n`;

    if (meal.healthBenefits?.length > 0) {
      text += `\n✨ BENEFITS: ${meal.healthBenefits.join(", ")}\n`;
    }

    text += `\n— Generated by SafeScan AI Meal Planner`;

    return text;
  };

  const generateShoppingListText = () => {
    let text = `🛒 SHOPPING LIST\n`;
    text += `━━━━━━━━━━━━━━━━━━━━\n`;
    shoppingList.forEach((item) => {
      text += `☐ ${item}\n`;
    });
    text += `\n— Generated by SafeScan`;
    return text;
  };

  const generateFullPlanText = () => {
    let text = `📅 MY MEAL PLAN\n`;
    text += `━━━━━━━━━━━━━━━━━━━━\n\n`;

    meals.forEach((meal, i) => {
      text += `${i + 1}. ${meal.name} (${meal.type})\n`;
      text += `   ⏱️ ${meal.prepTime} prep | 🔥 ${meal.nutrition.calories} cal\n\n`;
    });

    if (shoppingList.length > 0) {
      text += `🛒 SHOPPING LIST:\n`;
      shoppingList.forEach((item) => {
        text += `☐ ${item}\n`;
      });
    }

    text += `\n— Generated by SafeScan AI Meal Planner`;
    return text;
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <Dialog open={isOpen} onOpenChange={setIsOpen}>
      <DialogTrigger asChild>
        <Button
          variant="outline"
          size="sm"
          className="gap-2 border-background/20 text-background hover:bg-background/10"
        >
          <Share2 className="w-4 h-4" />
          Share
        </Button>
      </DialogTrigger>
      <DialogContent className="bg-foreground border-background/20 max-w-md">
        <DialogHeader>
          <DialogTitle className="text-background flex items-center gap-2">
            <Share2 className="w-5 h-5" />
            Share {singleMeal ? "Recipe" : "Meal Plan"}
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-3 mt-4">
          {/* Print Option */}
          <Button
            variant="outline"
            onClick={handlePrint}
            className="w-full justify-start gap-3 border-background/20 text-background hover:bg-background/10"
          >
            <Printer className="w-5 h-5" />
            <div className="text-left">
              <p className="font-medium">Print Recipe</p>
              <p className="text-xs text-background/50">Print-friendly format</p>
            </div>
          </Button>

          {/* Copy Recipe */}
          {singleMeal && (
            <Button
              variant="outline"
              onClick={() => copyToClipboard(generateRecipeText(singleMeal), "Recipe")}
              className="w-full justify-start gap-3 border-background/20 text-background hover:bg-background/10"
            >
              {copied === "Recipe" ? (
                <Check className="w-5 h-5 text-safe" />
              ) : (
                <Copy className="w-5 h-5" />
              )}
              <div className="text-left">
                <p className="font-medium">Copy Recipe</p>
                <p className="text-xs text-background/50">As formatted text</p>
              </div>
            </Button>
          )}

          {/* Copy Full Plan */}
          {mealPlan && meals.length > 0 && (
            <Button
              variant="outline"
              onClick={() => copyToClipboard(generateFullPlanText(), "Meal Plan")}
              className="w-full justify-start gap-3 border-background/20 text-background hover:bg-background/10"
            >
              {copied === "Meal Plan" ? (
                <Check className="w-5 h-5 text-safe" />
              ) : (
                <MessageSquare className="w-5 h-5" />
              )}
              <div className="text-left">
                <p className="font-medium">Copy Full Plan</p>
                <p className="text-xs text-background/50">All meals summary</p>
              </div>
            </Button>
          )}

          {/* Copy Shopping List */}
          {shoppingList.length > 0 && (
            <Button
              variant="outline"
              onClick={() => copyToClipboard(generateShoppingListText(), "Shopping List")}
              className="w-full justify-start gap-3 border-background/20 text-background hover:bg-background/10"
            >
              {copied === "Shopping List" ? (
                <Check className="w-5 h-5 text-safe" />
              ) : (
                <ClipboardList className="w-5 h-5" />
              )}
              <div className="text-left">
                <p className="font-medium">Copy Shopping List</p>
                <p className="text-xs text-background/50">Checklist format</p>
              </div>
            </Button>
          )}
        </div>

        {/* Hidden printable content */}
        <div className="hidden print:block">
          {singleMeal && (
            <PrintableRecipe ref={printRef} meal={singleMeal} />
          )}
          {!singleMeal && meals.length > 0 && (
            <div className="space-y-8">
              {meals.map((meal, i) => (
                <PrintableRecipe key={i} meal={meal} showLogo={i === 0} />
              ))}
            </div>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
};
